// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_fastSpMatViewSum
NumericVector C_fastSpMatViewSum(arma::sp_mat X, arma::vec idx, int dim, int threads);
RcppExport SEXP _actionet_C_fastSpMatViewSum(SEXP XSEXP, SEXP idxSEXP, SEXP dimSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastSpMatViewSum(X, idx, dim, threads));
    return rcpp_result_gen;
END_RCPP
}
// C_runAA
Rcpp::List C_runAA(arma::mat& A, arma::mat& W0, int max_it, double tol);
RcppExport SEXP _actionet_C_runAA(SEXP ASEXP, SEXP W0SEXP, SEXP max_itSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runAA(A, W0, max_it, tol));
    return rcpp_result_gen;
END_RCPP
}
// C_decompACTION
Rcpp::List C_decompACTION(arma::mat& S_r, int k_min, int k_max, int max_it, double tol, int thread_no);
RcppExport SEXP _actionet_C_decompACTION(SEXP S_rSEXP, SEXP k_minSEXP, SEXP k_maxSEXP, SEXP max_itSEXP, SEXP tolSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S_r(S_rSEXP);
    Rcpp::traits::input_parameter< int >::type k_min(k_minSEXP);
    Rcpp::traits::input_parameter< int >::type k_max(k_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_decompACTION(S_r, k_min, k_max, max_it, tol, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_runACTION
Rcpp::List C_runACTION(arma::mat& S_r, int k_min, int k_max, int max_it, double tol, double spec_th, int min_obs, int thread_no);
RcppExport SEXP _actionet_C_runACTION(SEXP S_rSEXP, SEXP k_minSEXP, SEXP k_maxSEXP, SEXP max_itSEXP, SEXP tolSEXP, SEXP spec_thSEXP, SEXP min_obsSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S_r(S_rSEXP);
    Rcpp::traits::input_parameter< int >::type k_min(k_minSEXP);
    Rcpp::traits::input_parameter< int >::type k_max(k_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type spec_th(spec_thSEXP);
    Rcpp::traits::input_parameter< int >::type min_obs(min_obsSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runACTION(S_r, k_min, k_max, max_it, tol, spec_th, min_obs, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_collectArchetypes
Rcpp::List C_collectArchetypes(const Rcpp::List& C_trace, const Rcpp::List& H_trace, double spec_th, int min_obs);
RcppExport SEXP _actionet_C_collectArchetypes(SEXP C_traceSEXP, SEXP H_traceSEXP, SEXP spec_thSEXP, SEXP min_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type C_trace(C_traceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type H_trace(H_traceSEXP);
    Rcpp::traits::input_parameter< double >::type spec_th(spec_thSEXP);
    Rcpp::traits::input_parameter< int >::type min_obs(min_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_collectArchetypes(C_trace, H_trace, spec_th, min_obs));
    return rcpp_result_gen;
END_RCPP
}
// C_mergeArchetypes
Rcpp::List C_mergeArchetypes(arma::mat& S_r, arma::mat& C_stacked, arma::mat& H_stacked, int thread_no);
RcppExport SEXP _actionet_C_mergeArchetypes(SEXP S_rSEXP, SEXP C_stackedSEXP, SEXP H_stackedSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S_r(S_rSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type C_stacked(C_stackedSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H_stacked(H_stackedSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_mergeArchetypes(S_r, C_stacked, H_stacked, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_reduceKernelSparse
Rcpp::List C_reduceKernelSparse(arma::sp_mat& S, int k, int svd_alg, int max_it, int seed, bool verbose);
RcppExport SEXP _actionet_C_reduceKernelSparse(SEXP SSEXP, SEXP kSEXP, SEXP svd_algSEXP, SEXP max_itSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type svd_alg(svd_algSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(C_reduceKernelSparse(S, k, svd_alg, max_it, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// C_reduceKernelDense
Rcpp::List C_reduceKernelDense(arma::mat& S, int k, int svd_alg, int max_it, int seed, bool verbose);
RcppExport SEXP _actionet_C_reduceKernelDense(SEXP SSEXP, SEXP kSEXP, SEXP svd_algSEXP, SEXP max_itSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type svd_alg(svd_algSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(C_reduceKernelDense(S, k, svd_alg, max_it, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// C_runSimplexRegression
arma::mat C_runSimplexRegression(arma::mat& A, arma::mat& B, bool computeXtX);
RcppExport SEXP _actionet_C_runSimplexRegression(SEXP ASEXP, SEXP BSEXP, SEXP computeXtXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type computeXtX(computeXtXSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runSimplexRegression(A, B, computeXtX));
    return rcpp_result_gen;
END_RCPP
}
// C_runSPA
Rcpp::List C_runSPA(arma::mat& A, int k);
RcppExport SEXP _actionet_C_runSPA(SEXP ASEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runSPA(A, k));
    return rcpp_result_gen;
END_RCPP
}
// C_computeFeatureStats
arma::mat C_computeFeatureStats(arma::sp_mat& G, arma::sp_mat& S, arma::sp_mat& X, int norm_type, double alpha, int max_it, bool approx, int thread_no, bool ignore_baseline);
RcppExport SEXP _actionet_C_computeFeatureStats(SEXP GSEXP, SEXP SSEXP, SEXP XSEXP, SEXP norm_typeSEXP, SEXP alphaSEXP, SEXP max_itSEXP, SEXP approxSEXP, SEXP thread_noSEXP, SEXP ignore_baselineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type norm_type(norm_typeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_baseline(ignore_baselineSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeFeatureStats(G, S, X, norm_type, alpha, max_it, approx, thread_no, ignore_baseline));
    return rcpp_result_gen;
END_RCPP
}
// C_computeFeatureStatsVision
arma::mat C_computeFeatureStatsVision(arma::sp_mat& G, arma::sp_mat& S, arma::sp_mat& X, int norm_type, double alpha, int max_it, bool approx, int thread_no);
RcppExport SEXP _actionet_C_computeFeatureStatsVision(SEXP GSEXP, SEXP SSEXP, SEXP XSEXP, SEXP norm_typeSEXP, SEXP alphaSEXP, SEXP max_itSEXP, SEXP approxSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type norm_type(norm_typeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeFeatureStatsVision(G, S, X, norm_type, alpha, max_it, approx, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_archetypeFeatureSpecificitySparse
Rcpp::List C_archetypeFeatureSpecificitySparse(arma::sp_mat& S, arma::mat& H, int thread_no);
RcppExport SEXP _actionet_C_archetypeFeatureSpecificitySparse(SEXP SSEXP, SEXP HSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_archetypeFeatureSpecificitySparse(S, H, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_archetypeFeatureSpecificityDense
Rcpp::List C_archetypeFeatureSpecificityDense(arma::mat& S, arma::mat& H, int thread_no);
RcppExport SEXP _actionet_C_archetypeFeatureSpecificityDense(SEXP SSEXP, SEXP HSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_archetypeFeatureSpecificityDense(S, H, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_computeFeatureSpecificitySparse
Rcpp::List C_computeFeatureSpecificitySparse(arma::sp_mat& S, arma::uvec& labels, int thread_no);
RcppExport SEXP _actionet_C_computeFeatureSpecificitySparse(SEXP SSEXP, SEXP labelsSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeFeatureSpecificitySparse(S, labels, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_computeFeatureSpecificityDense
Rcpp::List C_computeFeatureSpecificityDense(arma::mat& S, arma::uvec& labels, int thread_no);
RcppExport SEXP _actionet_C_computeFeatureSpecificityDense(SEXP SSEXP, SEXP labelsSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeFeatureSpecificityDense(S, labels, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_orthogonalizeBatchEffect
Rcpp::List C_orthogonalizeBatchEffect(arma::sp_mat& S, arma::mat& old_S_r, arma::mat& old_V, arma::mat& old_A, arma::mat& old_B, arma::vec& old_sigma, arma::mat& design);
RcppExport SEXP _actionet_C_orthogonalizeBatchEffect(SEXP SSEXP, SEXP old_S_rSEXP, SEXP old_VSEXP, SEXP old_ASEXP, SEXP old_BSEXP, SEXP old_sigmaSEXP, SEXP designSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_S_r(old_S_rSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_V(old_VSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_A(old_ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_B(old_BSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type old_sigma(old_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    rcpp_result_gen = Rcpp::wrap(C_orthogonalizeBatchEffect(S, old_S_r, old_V, old_A, old_B, old_sigma, design));
    return rcpp_result_gen;
END_RCPP
}
// C_orthogonalizeBatchEffect_full
Rcpp::List C_orthogonalizeBatchEffect_full(arma::mat& S, arma::mat& old_S_r, arma::mat& old_V, arma::mat& old_A, arma::mat& old_B, arma::vec& old_sigma, arma::mat& design);
RcppExport SEXP _actionet_C_orthogonalizeBatchEffect_full(SEXP SSEXP, SEXP old_S_rSEXP, SEXP old_VSEXP, SEXP old_ASEXP, SEXP old_BSEXP, SEXP old_sigmaSEXP, SEXP designSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_S_r(old_S_rSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_V(old_VSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_A(old_ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_B(old_BSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type old_sigma(old_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    rcpp_result_gen = Rcpp::wrap(C_orthogonalizeBatchEffect_full(S, old_S_r, old_V, old_A, old_B, old_sigma, design));
    return rcpp_result_gen;
END_RCPP
}
// C_orthogonalizeBasal
Rcpp::List C_orthogonalizeBasal(arma::sp_mat& S, arma::mat& old_S_r, arma::mat& old_V, arma::mat& old_A, arma::mat& old_B, arma::vec& old_sigma, arma::mat& basal);
RcppExport SEXP _actionet_C_orthogonalizeBasal(SEXP SSEXP, SEXP old_S_rSEXP, SEXP old_VSEXP, SEXP old_ASEXP, SEXP old_BSEXP, SEXP old_sigmaSEXP, SEXP basalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_S_r(old_S_rSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_V(old_VSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_A(old_ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_B(old_BSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type old_sigma(old_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type basal(basalSEXP);
    rcpp_result_gen = Rcpp::wrap(C_orthogonalizeBasal(S, old_S_r, old_V, old_A, old_B, old_sigma, basal));
    return rcpp_result_gen;
END_RCPP
}
// C_orthogonalizeBasal_full
Rcpp::List C_orthogonalizeBasal_full(arma::mat& S, arma::mat& old_S_r, arma::mat& old_V, arma::mat& old_A, arma::mat& old_B, arma::vec& old_sigma, arma::mat& basal);
RcppExport SEXP _actionet_C_orthogonalizeBasal_full(SEXP SSEXP, SEXP old_S_rSEXP, SEXP old_VSEXP, SEXP old_ASEXP, SEXP old_BSEXP, SEXP old_sigmaSEXP, SEXP basalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_S_r(old_S_rSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_V(old_VSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_A(old_ASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type old_B(old_BSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type old_sigma(old_sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type basal(basalSEXP);
    rcpp_result_gen = Rcpp::wrap(C_orthogonalizeBasal_full(S, old_S_r, old_V, old_A, old_B, old_sigma, basal));
    return rcpp_result_gen;
END_RCPP
}
// C_runSVDSparse
Rcpp::List C_runSVDSparse(arma::sp_mat& A, int k, int max_it, int seed, int algorithm, bool verbose);
RcppExport SEXP _actionet_C_runSVDSparse(SEXP ASEXP, SEXP kSEXP, SEXP max_itSEXP, SEXP seedSEXP, SEXP algorithmSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runSVDSparse(A, k, max_it, seed, algorithm, verbose));
    return rcpp_result_gen;
END_RCPP
}
// C_runSVDDense
Rcpp::List C_runSVDDense(arma::mat& A, int k, int max_it, int seed, int algorithm, bool verbose);
RcppExport SEXP _actionet_C_runSVDDense(SEXP ASEXP, SEXP kSEXP, SEXP max_itSEXP, SEXP seedSEXP, SEXP algorithmSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runSVDDense(A, k, max_it, seed, algorithm, verbose));
    return rcpp_result_gen;
END_RCPP
}
// C_perturbedSVD
Rcpp::List C_perturbedSVD(arma::mat u, arma::vec d, arma::mat v, arma::mat A, arma::mat B);
RcppExport SEXP _actionet_C_perturbedSVD(SEXP uSEXP, SEXP dSEXP, SEXP vSEXP, SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(C_perturbedSVD(u, d, v, A, B));
    return rcpp_result_gen;
END_RCPP
}
// C_buildNetwork
arma::sp_mat C_buildNetwork(const arma::mat& H, std::string algorithm, std::string distance_metric, double density, int thread_no, double M, double ef_construction, double ef, bool mutual_edges_only, int k);
RcppExport SEXP _actionet_C_buildNetwork(SEXP HSEXP, SEXP algorithmSEXP, SEXP distance_metricSEXP, SEXP densitySEXP, SEXP thread_noSEXP, SEXP MSEXP, SEXP ef_constructionSEXP, SEXP efSEXP, SEXP mutual_edges_onlySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< std::string >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< std::string >::type distance_metric(distance_metricSEXP);
    Rcpp::traits::input_parameter< double >::type density(densitySEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type ef_construction(ef_constructionSEXP);
    Rcpp::traits::input_parameter< double >::type ef(efSEXP);
    Rcpp::traits::input_parameter< bool >::type mutual_edges_only(mutual_edges_onlySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(C_buildNetwork(H, algorithm, distance_metric, density, thread_no, M, ef_construction, ef, mutual_edges_only, k));
    return rcpp_result_gen;
END_RCPP
}
// C_runLPA
arma::vec C_runLPA(arma::sp_mat& G, arma::vec& labels, double lambda, int iters, double sig_threshold, Rcpp::Nullable<Rcpp::IntegerVector> fixed_labels_, int thread_no);
RcppExport SEXP _actionet_C_runLPA(SEXP GSEXP, SEXP labelsSEXP, SEXP lambdaSEXP, SEXP itersSEXP, SEXP sig_thresholdSEXP, SEXP fixed_labels_SEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type iters(itersSEXP);
    Rcpp::traits::input_parameter< double >::type sig_threshold(sig_thresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fixed_labels_(fixed_labels_SEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_runLPA(G, labels, lambda, iters, sig_threshold, fixed_labels_, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_computeNetworkDiffusion
arma::mat C_computeNetworkDiffusion(arma::sp_mat& G, arma::mat& X0, double alpha, int max_it, int thread_no, bool approx, int norm_method, double tol);
RcppExport SEXP _actionet_C_computeNetworkDiffusion(SEXP GSEXP, SEXP X0SEXP, SEXP alphaSEXP, SEXP max_itSEXP, SEXP thread_noSEXP, SEXP approxSEXP, SEXP norm_methodSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< int >::type norm_method(norm_methodSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeNetworkDiffusion(G, X0, alpha, max_it, thread_no, approx, norm_method, tol));
    return rcpp_result_gen;
END_RCPP
}
// C_computeCoreness
arma::uvec C_computeCoreness(arma::sp_mat& G);
RcppExport SEXP _actionet_C_computeCoreness(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeCoreness(G));
    return rcpp_result_gen;
END_RCPP
}
// C_computeArchetypeCentrality
arma::vec C_computeArchetypeCentrality(arma::sp_mat& G, const arma::uvec& sample_assignments);
RcppExport SEXP _actionet_C_computeArchetypeCentrality(SEXP GSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeArchetypeCentrality(G, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_autocorrelation_Moran_parametric
Rcpp::List C_autocorrelation_Moran_parametric(const arma::sp_mat& G, const arma::mat& scores, int normalization_method, int thread_no);
RcppExport SEXP _actionet_C_autocorrelation_Moran_parametric(SEXP GSEXP, SEXP scoresSEXP, SEXP normalization_methodSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< int >::type normalization_method(normalization_methodSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_autocorrelation_Moran_parametric(G, scores, normalization_method, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_autocorrelation_Moran
Rcpp::List C_autocorrelation_Moran(const arma::sp_mat& G, const arma::mat& scores, int normalization_method, int perm_no, int thread_no);
RcppExport SEXP _actionet_C_autocorrelation_Moran(SEXP GSEXP, SEXP scoresSEXP, SEXP normalization_methodSEXP, SEXP perm_noSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< int >::type normalization_method(normalization_methodSEXP);
    Rcpp::traits::input_parameter< int >::type perm_no(perm_noSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_autocorrelation_Moran(G, scores, normalization_method, perm_no, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_autocorrelation_Geary
Rcpp::List C_autocorrelation_Geary(const arma::sp_mat& G, const arma::mat& scores, int normalization_method, int perm_no, int thread_no);
RcppExport SEXP _actionet_C_autocorrelation_Geary(SEXP GSEXP, SEXP scoresSEXP, SEXP normalization_methodSEXP, SEXP perm_noSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< int >::type normalization_method(normalization_methodSEXP);
    Rcpp::traits::input_parameter< int >::type perm_no(perm_noSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_autocorrelation_Geary(G, scores, normalization_method, perm_no, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGraphLabelEnrichment
arma::mat C_computeGraphLabelEnrichment(const arma::sp_mat& G, arma::mat& scores, int thread_no);
RcppExport SEXP _actionet_C_computeGraphLabelEnrichment(SEXP GSEXP, SEXP scoresSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGraphLabelEnrichment(G, scores, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_assess_enrichment
Rcpp::List C_assess_enrichment(arma::mat& scores, arma::sp_mat& associations, int thread_no);
RcppExport SEXP _actionet_C_assess_enrichment(SEXP scoresSEXP, SEXP associationsSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type associations(associationsSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_assess_enrichment(scores, associations, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGroupedRowSumsSparse
arma::mat C_computeGroupedRowSumsSparse(arma::sp_mat& S, arma::vec& sample_assignments);
RcppExport SEXP _actionet_C_computeGroupedRowSumsSparse(SEXP SSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGroupedRowSumsSparse(S, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGroupedRowSumsDense
arma::mat C_computeGroupedRowSumsDense(arma::mat& S, arma::vec& sample_assignments);
RcppExport SEXP _actionet_C_computeGroupedRowSumsDense(SEXP SSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGroupedRowSumsDense(S, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGroupedRowMeansSparse
arma::mat C_computeGroupedRowMeansSparse(arma::sp_mat& S, arma::vec& sample_assignments);
RcppExport SEXP _actionet_C_computeGroupedRowMeansSparse(SEXP SSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGroupedRowMeansSparse(S, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGroupedRowMeansDense
arma::mat C_computeGroupedRowMeansDense(arma::mat& S, arma::vec& sample_assignments);
RcppExport SEXP _actionet_C_computeGroupedRowMeansDense(SEXP SSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGroupedRowMeansDense(S, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGroupedRowVarsSparse
arma::mat C_computeGroupedRowVarsSparse(arma::sp_mat& S, arma::vec& sample_assignments);
RcppExport SEXP _actionet_C_computeGroupedRowVarsSparse(SEXP SSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGroupedRowVarsSparse(S, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_computeGroupedRowVarsDense
arma::mat C_computeGroupedRowVarsDense(arma::mat& S, arma::vec& sample_assignments);
RcppExport SEXP _actionet_C_computeGroupedRowVarsDense(SEXP SSEXP, SEXP sample_assignmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sample_assignments(sample_assignmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeGroupedRowVarsDense(S, sample_assignments));
    return rcpp_result_gen;
END_RCPP
}
// C_normalizeMatrixSparse
arma::sp_mat C_normalizeMatrixSparse(arma::sp_mat& X, unsigned int p, unsigned int dim);
RcppExport SEXP _actionet_C_normalizeMatrixSparse(SEXP XSEXP, SEXP pSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(C_normalizeMatrixSparse(X, p, dim));
    return rcpp_result_gen;
END_RCPP
}
// C_normalizeMatrixDense
arma::mat C_normalizeMatrixDense(arma::mat& X, unsigned int p, unsigned int dim);
RcppExport SEXP _actionet_C_normalizeMatrixDense(SEXP XSEXP, SEXP pSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type p(pSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(C_normalizeMatrixDense(X, p, dim));
    return rcpp_result_gen;
END_RCPP
}
// C_scaleMatrixDense
arma::mat C_scaleMatrixDense(arma::mat& X, arma::vec& v, unsigned int dim);
RcppExport SEXP _actionet_C_scaleMatrixDense(SEXP XSEXP, SEXP vSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(C_scaleMatrixDense(X, v, dim));
    return rcpp_result_gen;
END_RCPP
}
// C_scaleMatrixSparse
arma::sp_mat C_scaleMatrixSparse(arma::sp_mat& X, arma::vec& v, unsigned int dim);
RcppExport SEXP _actionet_C_scaleMatrixSparse(SEXP XSEXP, SEXP vSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(C_scaleMatrixSparse(X, v, dim));
    return rcpp_result_gen;
END_RCPP
}
// C_normalizeGraph
arma::sp_mat C_normalizeGraph(arma::sp_mat& G, int norm_type);
RcppExport SEXP _actionet_C_normalizeGraph(SEXP GSEXP, SEXP norm_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type norm_type(norm_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(C_normalizeGraph(G, norm_type));
    return rcpp_result_gen;
END_RCPP
}
// C_MWM_hungarian
arma::mat C_MWM_hungarian(arma::mat& G);
RcppExport SEXP _actionet_C_MWM_hungarian(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(C_MWM_hungarian(G));
    return rcpp_result_gen;
END_RCPP
}
// C_MWM_rank1
arma::umat C_MWM_rank1(const arma::vec& u, const arma::vec& v, double u_threshold, double v_threshold);
RcppExport SEXP _actionet_C_MWM_rank1(SEXP uSEXP, SEXP vSEXP, SEXP u_thresholdSEXP, SEXP v_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type u_threshold(u_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type v_threshold(v_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(C_MWM_rank1(u, v, u_threshold, v_threshold));
    return rcpp_result_gen;
END_RCPP
}
// C_xicor
arma::vec C_xicor(arma::vec xvec, arma::vec yvec, bool compute_pval, int seed);
RcppExport SEXP _actionet_C_xicor(SEXP xvecSEXP, SEXP yvecSEXP, SEXP compute_pvalSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xvec(xvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_pval(compute_pvalSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(C_xicor(xvec, yvec, compute_pval, seed));
    return rcpp_result_gen;
END_RCPP
}
// C_XICOR
Rcpp::List C_XICOR(arma::mat& X, arma::mat& Y, bool compute_pval, int seed, int thread_no);
RcppExport SEXP _actionet_C_XICOR(SEXP XSEXP, SEXP YSEXP, SEXP compute_pvalSEXP, SEXP seedSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_pval(compute_pvalSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_XICOR(X, Y, compute_pval, seed, thread_no));
    return rcpp_result_gen;
END_RCPP
}
// C_layoutNetwork
arma::mat C_layoutNetwork(arma::sp_mat& G, arma::mat& initial_coordinates, std::string method, unsigned int n_components, float spread, float min_dist, unsigned int n_epochs, float learning_rate, float repulsion_strength, float negative_sample_rate, bool approx_pow, bool pcg_rand, bool batch, unsigned int grain_size, int seed, int thread_no, bool verbose, float a, float b, std::string opt_method, float alpha, float beta1, float beta2, float eps);
RcppExport SEXP _actionet_C_layoutNetwork(SEXP GSEXP, SEXP initial_coordinatesSEXP, SEXP methodSEXP, SEXP n_componentsSEXP, SEXP spreadSEXP, SEXP min_distSEXP, SEXP n_epochsSEXP, SEXP learning_rateSEXP, SEXP repulsion_strengthSEXP, SEXP negative_sample_rateSEXP, SEXP approx_powSEXP, SEXP pcg_randSEXP, SEXP batchSEXP, SEXP grain_sizeSEXP, SEXP seedSEXP, SEXP thread_noSEXP, SEXP verboseSEXP, SEXP aSEXP, SEXP bSEXP, SEXP opt_methodSEXP, SEXP alphaSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type initial_coordinates(initial_coordinatesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_components(n_componentsSEXP);
    Rcpp::traits::input_parameter< float >::type spread(spreadSEXP);
    Rcpp::traits::input_parameter< float >::type min_dist(min_distSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< float >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< float >::type repulsion_strength(repulsion_strengthSEXP);
    Rcpp::traits::input_parameter< float >::type negative_sample_rate(negative_sample_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type approx_pow(approx_powSEXP);
    Rcpp::traits::input_parameter< bool >::type pcg_rand(pcg_randSEXP);
    Rcpp::traits::input_parameter< bool >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type grain_size(grain_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< float >::type a(aSEXP);
    Rcpp::traits::input_parameter< float >::type b(bSEXP);
    Rcpp::traits::input_parameter< std::string >::type opt_method(opt_methodSEXP);
    Rcpp::traits::input_parameter< float >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< float >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< float >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< float >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(C_layoutNetwork(G, initial_coordinates, method, n_components, spread, min_dist, n_epochs, learning_rate, repulsion_strength, negative_sample_rate, approx_pow, pcg_rand, batch, grain_size, seed, thread_no, verbose, a, b, opt_method, alpha, beta1, beta2, eps));
    return rcpp_result_gen;
END_RCPP
}
// C_computeNodeColors
arma::mat C_computeNodeColors(const arma::mat& coordinates, int thread_no);
RcppExport SEXP _actionet_C_computeNodeColors(SEXP coordinatesSEXP, SEXP thread_noSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type coordinates(coordinatesSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    rcpp_result_gen = Rcpp::wrap(C_computeNodeColors(coordinates, thread_no));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_actionet_C_fastSpMatViewSum", (DL_FUNC) &_actionet_C_fastSpMatViewSum, 4},
    {"_actionet_C_runAA", (DL_FUNC) &_actionet_C_runAA, 4},
    {"_actionet_C_decompACTION", (DL_FUNC) &_actionet_C_decompACTION, 6},
    {"_actionet_C_runACTION", (DL_FUNC) &_actionet_C_runACTION, 8},
    {"_actionet_C_collectArchetypes", (DL_FUNC) &_actionet_C_collectArchetypes, 4},
    {"_actionet_C_mergeArchetypes", (DL_FUNC) &_actionet_C_mergeArchetypes, 4},
    {"_actionet_C_reduceKernelSparse", (DL_FUNC) &_actionet_C_reduceKernelSparse, 6},
    {"_actionet_C_reduceKernelDense", (DL_FUNC) &_actionet_C_reduceKernelDense, 6},
    {"_actionet_C_runSimplexRegression", (DL_FUNC) &_actionet_C_runSimplexRegression, 3},
    {"_actionet_C_runSPA", (DL_FUNC) &_actionet_C_runSPA, 2},
    {"_actionet_C_computeFeatureStats", (DL_FUNC) &_actionet_C_computeFeatureStats, 9},
    {"_actionet_C_computeFeatureStatsVision", (DL_FUNC) &_actionet_C_computeFeatureStatsVision, 8},
    {"_actionet_C_archetypeFeatureSpecificitySparse", (DL_FUNC) &_actionet_C_archetypeFeatureSpecificitySparse, 3},
    {"_actionet_C_archetypeFeatureSpecificityDense", (DL_FUNC) &_actionet_C_archetypeFeatureSpecificityDense, 3},
    {"_actionet_C_computeFeatureSpecificitySparse", (DL_FUNC) &_actionet_C_computeFeatureSpecificitySparse, 3},
    {"_actionet_C_computeFeatureSpecificityDense", (DL_FUNC) &_actionet_C_computeFeatureSpecificityDense, 3},
    {"_actionet_C_orthogonalizeBatchEffect", (DL_FUNC) &_actionet_C_orthogonalizeBatchEffect, 7},
    {"_actionet_C_orthogonalizeBatchEffect_full", (DL_FUNC) &_actionet_C_orthogonalizeBatchEffect_full, 7},
    {"_actionet_C_orthogonalizeBasal", (DL_FUNC) &_actionet_C_orthogonalizeBasal, 7},
    {"_actionet_C_orthogonalizeBasal_full", (DL_FUNC) &_actionet_C_orthogonalizeBasal_full, 7},
    {"_actionet_C_runSVDSparse", (DL_FUNC) &_actionet_C_runSVDSparse, 6},
    {"_actionet_C_runSVDDense", (DL_FUNC) &_actionet_C_runSVDDense, 6},
    {"_actionet_C_perturbedSVD", (DL_FUNC) &_actionet_C_perturbedSVD, 5},
    {"_actionet_C_buildNetwork", (DL_FUNC) &_actionet_C_buildNetwork, 10},
    {"_actionet_C_runLPA", (DL_FUNC) &_actionet_C_runLPA, 7},
    {"_actionet_C_computeNetworkDiffusion", (DL_FUNC) &_actionet_C_computeNetworkDiffusion, 8},
    {"_actionet_C_computeCoreness", (DL_FUNC) &_actionet_C_computeCoreness, 1},
    {"_actionet_C_computeArchetypeCentrality", (DL_FUNC) &_actionet_C_computeArchetypeCentrality, 2},
    {"_actionet_C_autocorrelation_Moran_parametric", (DL_FUNC) &_actionet_C_autocorrelation_Moran_parametric, 4},
    {"_actionet_C_autocorrelation_Moran", (DL_FUNC) &_actionet_C_autocorrelation_Moran, 5},
    {"_actionet_C_autocorrelation_Geary", (DL_FUNC) &_actionet_C_autocorrelation_Geary, 5},
    {"_actionet_C_computeGraphLabelEnrichment", (DL_FUNC) &_actionet_C_computeGraphLabelEnrichment, 3},
    {"_actionet_C_assess_enrichment", (DL_FUNC) &_actionet_C_assess_enrichment, 3},
    {"_actionet_C_computeGroupedRowSumsSparse", (DL_FUNC) &_actionet_C_computeGroupedRowSumsSparse, 2},
    {"_actionet_C_computeGroupedRowSumsDense", (DL_FUNC) &_actionet_C_computeGroupedRowSumsDense, 2},
    {"_actionet_C_computeGroupedRowMeansSparse", (DL_FUNC) &_actionet_C_computeGroupedRowMeansSparse, 2},
    {"_actionet_C_computeGroupedRowMeansDense", (DL_FUNC) &_actionet_C_computeGroupedRowMeansDense, 2},
    {"_actionet_C_computeGroupedRowVarsSparse", (DL_FUNC) &_actionet_C_computeGroupedRowVarsSparse, 2},
    {"_actionet_C_computeGroupedRowVarsDense", (DL_FUNC) &_actionet_C_computeGroupedRowVarsDense, 2},
    {"_actionet_C_normalizeMatrixSparse", (DL_FUNC) &_actionet_C_normalizeMatrixSparse, 3},
    {"_actionet_C_normalizeMatrixDense", (DL_FUNC) &_actionet_C_normalizeMatrixDense, 3},
    {"_actionet_C_scaleMatrixDense", (DL_FUNC) &_actionet_C_scaleMatrixDense, 3},
    {"_actionet_C_scaleMatrixSparse", (DL_FUNC) &_actionet_C_scaleMatrixSparse, 3},
    {"_actionet_C_normalizeGraph", (DL_FUNC) &_actionet_C_normalizeGraph, 2},
    {"_actionet_C_MWM_hungarian", (DL_FUNC) &_actionet_C_MWM_hungarian, 1},
    {"_actionet_C_MWM_rank1", (DL_FUNC) &_actionet_C_MWM_rank1, 4},
    {"_actionet_C_xicor", (DL_FUNC) &_actionet_C_xicor, 4},
    {"_actionet_C_XICOR", (DL_FUNC) &_actionet_C_XICOR, 5},
    {"_actionet_C_layoutNetwork", (DL_FUNC) &_actionet_C_layoutNetwork, 24},
    {"_actionet_C_computeNodeColors", (DL_FUNC) &_actionet_C_computeNodeColors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_actionet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
